### PR TITLE
Fixes #76 Adds array type specialization

### LINKED ISSUE #76: omi script provider does not compile on ubuntu 16 and probably others
A build break. 
g++ -g -std=gnu++98 -fPIC -Wall -fvisibility=hidden -fno-strict-aliasing -fstack-protector-all -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -DENCRYPT_DECRPYT -DGSS_USE_IOV=1 -D_BSD_SOURCE -fpermissive -DPRINT_BOOKENDS=0 -I/home/v-brucc/omi/Unix/output/include -I//home/v-brucc/omi/Unix/output/include  -c -MD mi_instance.cpp -o /home/v-brucc/scriptprovider/output/obj/mi_instance.o
In file included from shared_protocol.hpp:9:0,
                 from mi_value.hpp:13,
                 from mi_instance.hpp:8,
                 from mi_instance.cpp:3:
unique_ptr.hpp: In instantiation of ‘struct util::unique_ptr_move<char [], util::default_delete<char []> >’:
shared_protocol.hpp:226:46:   required from ‘int protocol::recv(std::__cxx11::basic_string<char_t, traits>*, socket_wrapper&) [with char_t = char; traits = std::char_traits<char>]’
mi_value.hpp:876:35:   required from ‘static int scx::MI_Array<TYPE_ID>::recv(scx::MI_Array<TYPE_ID>::Ptr*, socket_wrapper&) [with unsigned int TYPE_ID = 29u; scx::MI_Array<TYPE_ID>::Ptr = util::internal_counted_ptr<scx::MI_Array<29u>, util::default_delete<scx::MI_Array<29u> > >]’
mi_instance.cpp:552:50:   required from here
unique_ptr.hpp:141:45: error: creating array of ‘char []’
     typename unique_ptr<T, D>::deleter_type m_deleter;
                                             ^
GNUmakefile:67: recipe for target '/home/v-brucc/scriptprovider/output/obj/mi_instance.o' failed
make[1]: *** [/home/v-brucc/scriptprovider/output/obj/mi_instance.o] Error 1
make[1]: Leaving directory '/home/v-brucc/scriptprovider/provider'
GNUmakefile:11: recipe for target 'SCRIPTPROVIDER' failed
make: *** [SCRIPTPROVIDER] Error 2
make -C /home/v-brucc/scriptprovider/provider install
make[1]: Entering directory '/home/v-brucc/scriptprovider/provider'
...compiling: mi_instance.o
g++ -g -std=gnu++98 -fPIC -Wall -fvisibility=hidden -fno-strict-aliasing -fstack-protector-all -D_GNU_SOURCE -D_XOPEN_SOURCE=600 -DENCRYPT_DECRPYT -DGSS_USE_IOV=1 -D_BSD_SOURCE -DPRINT_BOOKENDS=0 -I/home/v-brucc/omi/Unix/output/include -I//home/v-brucc/omi/Unix/output/include  -c -MD mi_instance.cpp -o /home/v-brucc/scriptprovider/output/obj/mi_instance.o
In file included from shared_protocol.hpp:9:0,
                 from mi_value.hpp:13,
                 from mi_instance.hpp:8,
                 from mi_instance.cpp:3:
unique_ptr.hpp: In instantiation of ‘struct util::unique_ptr_move<char [], util::default_delete<char []> >’:
shared_protocol.hpp:226:46:   required from ‘int protocol::recv(std::__cxx11::basic_string<char_t, traits>*, socket_wrapper&) [with char_t = char; traits = std::char_traits<char>]’
mi_value.hpp:876:35:   required from ‘static int scx::MI_Array<TYPE_ID>::recv(scx::MI_Array<TYPE_ID>::Ptr*, socket_wrapper&) [with unsigned int TYPE_ID = 29u; scx::MI_Array<TYPE_ID>::Ptr = util::internal_counted_ptr<scx::MI_Array<29u>, util::default_delete<scx::MI_Array<29u> > >]’
mi_instance.cpp:552:50:   required from here
unique_ptr.hpp:141:45: error: creating array of ‘char []’
     typename unique_ptr<T, D>::deleter_type m_deleter;
                                             ^
GNUmakefile:67: recipe for target '/home/v-brucc/scriptprovider/output/obj/mi_instance.o' failed
make[1]: *** [/home/v-brucc/scriptprovider/output/obj/mi_instance.o] Error 1
make[1]: Leaving directory '/home/v-brucc/scriptprovider/provider'

### PR DESCRIPTION
**Pull request by c64cosmin**
Fixes the template by adding the missing variant.

### CODE REVIEW

File: provider/unique_ptr.hpp [hunk 1]
```diff
@@ -180,6 +179,65 @@ unique_ptr_move<T, D>::unique_ptr_move (
 }
 
 
+// unique_ptr_move (array specialization)
+//------------------------------------------------------------------------------
+template<typename T, typename D>
+struct unique_ptr_move<T[], D>
```
Comment (EMumau) [inline provider/unique_ptr.hpp]: There shouldn't have to be a partial specialization for arrays for this class.  I know that there is a way to do this without one.  There should be a way for unique_ptr_move to typename the correct unique_ptr to avoid this code duplication.
Writing a specialization for this violates the idea of generic programming.

**Comment by EMumau** [comment]
I don't have the time today to give this the attention that I would like to.  I plan to look at this on Tuesday, December 4th.

**Review by EMumau — CHANGES_REQUESTED** [review]
Sorry that it has taken me so long to review this.
I wanted to have time to investigate thoroughly.
There is a much simpler solution.  If you revert your changes to head, you can:
    1.  In the declaration for the template class unique_ptr that is partially specialized for arrays, change the typedef to move_type [line 84] from "typedef unique_ptr_move<T[], D> move_type;" to "typedef unique_ptr_move<T, D> move_type;"  (note removing the array brackets.)
    2.  change the signature in the implementation of the unique_ptr specialized for arrays constructor that is overloaded for unique_ptr_move [line 388], change "unique_ptr_move<T[], D> const& move_ref" to "typename unique_ptr<T[], D>::move_type const& move_ref".

FWIW: There are a lot of unit tests in scriptprovider/test/test.cpp that are disabled because they are commented out.  I un-commented the tests with those changes and everything passed on 64-sles-10 and ubuntu16.  I don't know if enabling the disabled tests would affect Jumping's tests.

**Comment by c64cosmin** [comment]
@EMumau Added the changes and it compiles for Ubuntu 16.04.

**Review by EMumau — APPROVED** [review]
LGTM.
